### PR TITLE
upload PF hadron calibration code

### PR DESCRIPTION
**Pull request by cghuh**
This is the PF hadron calibration code that works on ROOT5 only.

### CODE REVIEW

**Comment by missirol** [comment]
Hi @cghuh , thanks for the update. Can you expand on why this only works for ROOT5?

Could you write here a set of commands to reproduce the issue from `lxplus`, so that we can figure out how to solve this? Obviously, we don't want to have to deal with different ROOT versions for different parts of the workflow.

**Comment by cghuh** [comment]
Hi @missirol  It make segmentation fault when run with ROOT6. I think this code made a long time ago. No one updated yet. I think it cause from ROOT6 doesn't support some library on ROOT5.

I didn't modify because it works on ROOT5. But if we need, I'll do them.

**Comment by missirol** [comment]
I think it's worth looking into this, and making it work with ROOT6.

Since, in principle, it should be possible to fix this without affecting the results, one would:
* get the results with ROOT5, as done now
* work on the script to make it work for ROOT6
* produce the outputs with ROOT6, and compare them to the ones from ROOT5, to verify that they are the same. Then we can keep the updated version of the scripts

if you share the steps to reproduce the issue, we can with this validation

**Comment by cghuh** [comment]
Ok. I'll do and report results when it ready.

**Comment by cghuh** [comment]
Hi @missirol , I modify code and now it works on ROOT6. This result shows same as ROOT5's.
I commit code again. Thanks.

**Pull request merged**
